name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install target
      uses: fsouza/rs-toolchain@v1.1.0
      with:
        toolchain: stable
        target: x86_64-pc-windows-gnu
        default: true
        override: true
        
    - name: Build
      run: cargo build -r --target=x86_64-pc-windows-gnu

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
          name: Preview
          path: ./target/x86_64-pc-windows-gnu/release/sc_starter.exe


