name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install target
      uses: fsouza/rs-toolchain@v1.1.0
      with:
        toolchain: stable
        target: x86_64-pc-windows-gnu
        default: true
        override: true
  
    - name: Test Env
      run: |
        echo gcc -v
        echo x86_64-w64-mingw32-gcc -v
    - name: Build
      run: cargo build -r --target=x86_64-pc-windows-gnu
