name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: rust-toolchain-reborn
      uses: crusty-pie/toolchain@v1.0.8
      with:
        toolchain: stable
        targets: x86_64-pc-windows-msvc
        default: true
        override: true
        
    - name: Build
      run: cargo build -r

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
          name: Preview
          path: ./target/release/SC_Starter.exe

